export const PROJECT_ICON_OPTIONS = [
  'pi-briefcase',
  'pi-code',
  'pi-home',
  'pi-book',
  'pi-heart',
  'pi-star',
  'pi-shopping-cart',
  'pi-wallet',
  'pi-users',
  'pi-graduation-cap',
  'pi-palette',
  'pi-camera',
  'pi-car',
  'pi-plane',
  'pi-flag',
  'pi-lightbulb',
  'pi-cog',
  'pi-globe',
  'pi-chart-line',
  'pi-folder',
] as const;

export const PROJECT_COLOR_OPTIONS = [
  '#ff9a3d',
  '#5b8def',
  '#34d399',
  '#f472b6',
  '#a78bfa',
  '#fbbf24',
  '#ef4444',
  '#64748b',
  '#14b8a6',
  '#f97316',
] as const;
